### PR TITLE
Added pytorch for python 3.7 docker file

### PR DESCRIPTION
**Pull request by MartinStrobel**
Added torch and torchvision to the modules for Python 3.7

### CODE REVIEW

**Review by fonglh — CHANGES_REQUESTED** [review]
Combine the commands into a single line as shown in the [documentation](https://pytorch.org/get-started/locally/#cuda-90-1)

Please also fix the typo in the commit message, thanks!

**Comment by trangmei** [comment]
image

Evaluator image size increased from 931MB to 3.1GB

To consider dropping support if there's any adverse effect on performance.

**Comment by MartinStrobel** [comment]
If that's an issue we could install a cpu only version (which is apparently a lot smaller)
The command would look something like:
pip3 install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

**Comment by trangmei** [comment]
Yeah sure let's try that.

The evaluator image with pytorch has been deployed, so you can try out by creating a question that would use this library, and include a solution as well. The package generated by coursemology can then be used to test future builds of python:3:7.

Try building the python:3.7 image locally on your machine, then follow this repo's README to test the new image using package created by the old image.

Feel free to ping me on slack if there's anything unexpected.

**Comment by knmnyn** [comment]
Thank you @trangmei @MartinStrobel !

**Pull request merged**
